# Generated by Django 4.1.2 on 2022-12-04 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mode_type', models.CharField(choices=[('ebike', 'EBIKE'), ('escooter', 'ESCOOTER'), ('emoped', 'EMOPED'), ('rideshare', 'RIDESHARE'), ('escootershare', 'ESCOOTERSHARE'), ('emopedshare', 'EMOPEDSHAR')], max_length=50)),
                ('pricing_type', models.CharField(choices=[('leasing', 'LEASING'), ('flat', 'FLAT'), ('time', 'TIME'), ('distance', 'DISTANCE')], max_length=50)),
                ('pricing_unit', models.CharField(choices=[('monthly', 'MONTHLY'), ('one-time', 'ONE-TIME'), ('yearly', 'YEARLY'), ('minute', 'MINUTE'), ('mile', 'MILE')], max_length=50)),
                ('pricing_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(null=True, upload_to='')),
                ('product_description', models.CharField(max_length=500)),
                ('metro_area', models.CharField(max_length=100)),
                ('transaction_name', models.CharField(max_length=100)),
                ('discount_amount', models.IntegerField(null=True)),
                ('discount_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_network_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website_url', models.URLField()),
                ('description', models.CharField(max_length=300)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('metro_area', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('setup_instructions', models.URLField()),
                ('provider_support', models.URLField()),
                ('merchant_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('leasing', 'LEASING'), ('flat', 'FLAT'), ('time', 'TIME'), ('distance', 'DISTANCE')], max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.IntegerField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portal.product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.provider')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='portal.provider'),
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=200)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.provider')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.transaction')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'transaction_name')},
        ),
    ]
