# Generated by Django 4.1.2 on 2022-12-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_product_options_transaction_flag_delete_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='product',
            name='mode_type',
            field=models.CharField(choices=[('EBIKE', 'EBIKE'), ('ESCOOTER', 'ESCOOTER'), ('EMOPED', 'EMOPED'), ('RIDESHARE', 'RIDESHARE'), ('ESCOOTERSHARE', 'ESCOOTERSHARE'), ('EMOPEDSHARE', 'EMOPEDSHAR')], max_length=50),
        ),
    ]
