# Generated by Django 4.1.2 on 2022-12-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_transaction_options_alter_product_mode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mode_type',
            field=models.CharField(choices=[('ebike', 'EBIKE'), ('escooter', 'ESCOOTER'), ('emoped', 'EMOPED'), ('rideshare', 'RIDESHARE'), ('escootershare', 'ESCOOTERSHARE'), ('emopedshare', 'EMOPEDSHAR'), ('EBIKE', 'EBIKE'), ('ESCOOTER', 'ESCOOTER'), ('EMOPED', 'EMOPED'), ('RIDESHARE', 'RIDESHARE'), ('ESCOOTERSHARE', 'ESCOOTERSHARE'), ('EMOPEDSHARE', 'EMOPEDSHAR')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pricing_type',
            field=models.CharField(choices=[('leasing', 'LEASING'), ('flat', 'FLAT'), ('time', 'TIME'), ('distance', 'DISTANCE'), ('LEASING', 'LEASING'), ('FLAT', 'FLAT'), ('TIME', 'TIME'), ('DISTANCE', 'DISTANCE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('leasing', 'LEASING'), ('flat', 'FLAT'), ('time', 'TIME'), ('distance', 'DISTANCE'), ('LEASING', 'LEASING'), ('FLAT', 'FLAT'), ('TIME', 'TIME'), ('DISTANCE', 'DISTANCE')], max_length=50),
        ),
    ]
